var l=console.log.bind(console),c=[];Object.size=function(obj){var size=0,key;for(key in obj){if(obj.hasOwnProperty(key))size++}
return size};function bytesToSize(bytes){var sizes=['Bytes','KB','MB','GB','TB'];if(bytes==0)return'0 Byte';var i=parseInt(Math.floor(Math.log(bytes)/Math.log(1024)));return Math.round(bytes/Math.pow(1024,i),2)+' '+sizes[i]}
function toLog(s){$('#textArea').append(s+"\n")}
$(document).ready(function(){["","Name","Size","Last Modify"].forEach(function(q){$('thead tr').append($('<th>').text(q))});if(window.File&&window.FileReader&&window.FileList&&window.Blob){}else{toLog('The File APIs are not fully supported in this browser.')}});function handleFileSelect(evt){var files=evt.target.files,tbody=$('<tbody>');for(var i=0,f;f=files[i];i++){var tr=$('<tr>'),t=[$('<img src="blank-file.png">').attr("style","width: 25px;"),$('<span class="fileName">').text(f.name),$('<span class="fileSize">').text(bytesToSize(f.size)),$('<span class="fileTime">').text(f.lastModifiedDate?f.lastModifiedDate.toLocaleDateString():'n/a')];t.forEach(function(q){$('<td>').append(q).appendTo(tr)});tr.appendTo(tbody);var reader=new FileReader();reader.onload=(function(theFile){return function(e){var content=e.target.result;if(content){c.push(content)}else{toLog("Error content...")}}})(f);reader.readAsText(f,"windows-1250")}
$('tbody').html("");$('table').append(tbody)}
function doSomethingWithFile(k){var ret=[],hdrs={};k.forEach(function(s){var lines=s.split("\n");$.each(lines,function(i,q){var p=q.split("|"),hh={};$.each(p,function(e,r){var o=r.indexOf("="),header=r.substr(0,o);if("undefined"==typeof hdrs[header]){hdrs[header]=Object.size(hdrs)}
hh[header]=r.substr(o+1).replace(String.fromCharCode(13),"")});ret.push(hh)})});return ret}
function handleFileSave(){if(c==undefined){toLog("Error Save");return!1}
toLog("Start...");setTimeout(function(){saveAsXLSx()},50)}
function saveAsXLSx(){var t0=performance.now();var wb=XLSX.utils.book_new();wb.Props={Title:"SheetJS Test",Subject:"Test",Author:"GreeN",CreatedDate:new Date(2020,3,19)};wb.SheetNames.push("Test Sheet");var ws_data=doSomethingWithFile(c);var ws=XLSX.utils.json_to_sheet(ws_data);wb.Sheets["Test Sheet"]=ws;var wbout=XLSX.write(wb,{bookType:'xlsx',type:'binary'});function s2ab(s){var buf=new ArrayBuffer(s.length);var view=new Uint8Array(buf);for(var i=0;i<s.length;i++)view[i]=s.charCodeAt(i)&0xFF;return buf}
saveAs(new Blob([s2ab(wbout)],{type:"application/octet-stream"}),$('#saveName').val());var t1=performance.now();toLog("Conversion took "+Math.round((t1-t0)/100)/10+" seconds.")}